# Generated by Django 5.2.1 on 2025-05-26 21:50

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CapacitySnapshot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('year', models.IntegerField()),
                ('month', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)])),
                ('total_capacity_hours', models.DecimalField(decimal_places=1, max_digits=8)),
                ('total_allocated_hours', models.DecimalField(decimal_places=1, max_digits=8)),
                ('total_revenue', models.DecimalField(decimal_places=2, max_digits=12)),
                ('utilization_rate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='capacity_snapshots', to='agency.company')),
            ],
            options={
                'unique_together': {('company', 'year', 'month')},
            },
        ),
        migrations.CreateModel(
            name='ProjectAllocation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('year', models.IntegerField()),
                ('month', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)])),
                ('allocated_hours', models.DecimalField(decimal_places=1, max_digits=6, validators=[django.core.validators.MinValueValidator(Decimal('0.1'))])),
                ('hourly_rate', models.DecimalField(decimal_places=2, max_digits=8)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='agency.project')),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_allocations', to='agency.userprofile')),
            ],
            options={
                'indexes': [models.Index(fields=['year', 'month'], name='agency_proj_year_3f2574_idx'), models.Index(fields=['project', 'year', 'month'], name='agency_proj_project_733e6b_idx'), models.Index(fields=['user_profile', 'year', 'month'], name='agency_proj_user_pr_ee76ba_idx')],
                'unique_together': {('project', 'user_profile', 'year', 'month')},
            },
        ),
    ]
