# Generated by Django 5.2.1 on 2025-05-26 22:35

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0002_capacitysnapshot_projectallocation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContractorExpense',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('year', models.IntegerField()),
                ('month', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)])),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('rent', 'Rent'), ('utilities', 'Utilities'), ('technology', 'Technology'), ('marketing', 'Marketing'), ('travel', 'Travel'), ('office', 'Office Supplies'), ('professional', 'Professional Services'), ('other', 'Other')], default='other', max_length=20)),
                ('monthly_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='MonthlyCost',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('cost_type', models.CharField(choices=[('payroll', 'Payroll'), ('contractor', 'Contractor'), ('tech_fees', 'Technology Fees'), ('rent', 'Rent'), ('utilities', 'Utilities'), ('marketing', 'Marketing'), ('travel', 'Travel'), ('office', 'Office Supplies'), ('professional', 'Professional Services'), ('other', 'Other')], max_length=20)),
                ('year', models.IntegerField()),
                ('month', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)])),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('frequency', models.CharField(choices=[('monthly', 'Monthly Recurring'), ('one_time', 'One Time'), ('annual', 'Annual'), ('quarterly', 'Quarterly')], default='monthly', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('is_billable', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='RecurringCost',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('cost_type', models.CharField(choices=[('payroll', 'Payroll'), ('contractor', 'Contractor'), ('tech_fees', 'Technology Fees'), ('rent', 'Rent'), ('utilities', 'Utilities'), ('marketing', 'Marketing'), ('travel', 'Travel'), ('office', 'Office Supplies'), ('professional', 'Professional Services'), ('other', 'Other')], max_length=20)),
                ('monthly_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='monthlyrevenue',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='capacitysnapshot',
            name='role_capacity_data',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='monthlyrevenue',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='monthly_revenues', to='agency.project'),
        ),
        migrations.AlterField(
            model_name='client',
            name='account_manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_clients', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_projects', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='monthlyrevenue',
            unique_together={('client', 'project', 'year', 'month', 'revenue_type')},
        ),
        migrations.AddIndex(
            model_name='capacitysnapshot',
            index=models.Index(fields=['company', 'year', 'month'], name='agency_capa_company_e08673_idx'),
        ),
        migrations.AddIndex(
            model_name='monthlyrevenue',
            index=models.Index(fields=['year', 'month', 'revenue_type'], name='agency_mont_year_fea912_idx'),
        ),
        migrations.AddIndex(
            model_name='monthlyrevenue',
            index=models.Index(fields=['company', 'year', 'month'], name='agency_mont_company_80f2a8_idx'),
        ),
        migrations.AddField(
            model_name='contractorexpense',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contractor_expenses', to='agency.company'),
        ),
        migrations.AddField(
            model_name='expense',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='agency.company'),
        ),
        migrations.AddField(
            model_name='monthlycost',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monthly_costs', to='agency.company'),
        ),
        migrations.AddField(
            model_name='monthlycost',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='costs', to='agency.project'),
        ),
        migrations.AddField(
            model_name='recurringcost',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recurring_costs', to='agency.company'),
        ),
        migrations.AddIndex(
            model_name='contractorexpense',
            index=models.Index(fields=['company', 'year', 'month'], name='agency_cont_company_dfe127_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='contractorexpense',
            unique_together={('name', 'company', 'year', 'month')},
        ),
        migrations.AddIndex(
            model_name='monthlycost',
            index=models.Index(fields=['company', 'year', 'month'], name='agency_mont_company_2ac7f7_idx'),
        ),
        migrations.AddIndex(
            model_name='monthlycost',
            index=models.Index(fields=['cost_type', 'year', 'month'], name='agency_mont_cost_ty_af05c2_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='monthlycost',
            unique_together={('company', 'name', 'year', 'month')},
        ),
    ]
