# Generated by Django 5.2.1 on 2025-05-28 19:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0005_cost'),
        ('agency', '0006_add_billable_rate_to_project'),
    ]

    operations = [
    ]
