# Generated by Django 5.2.1 on 2025-05-28 20:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0007_merge_20250528_1933'),
        ('agency', '0008_project_team_members'),
    ]

    operations = [
    ]
