# Generated by Django 5.2.1 on 2025-05-28 22:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0010_add_is_project_manager'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='monthlycost',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='monthlycost',
            name='company',
        ),
        migrations.RemoveField(
            model_name='monthlycost',
            name='project',
        ),
        migrations.RemoveField(
            model_name='recurringcost',
            name='company',
        ),
        migrations.RemoveIndex(
            model_name='contractorexpense',
            name='agency_cont_company_dfe127_idx',
        ),
        migrations.RenameIndex(
            model_name='cost',
            new_name='agency_cost_company_d15a4a_idx',
            old_name='agency_cost_company_start_idx',
        ),
        migrations.RenameIndex(
            model_name='cost',
            new_name='agency_cost_cost_ty_ef4917_idx',
            old_name='agency_cost_type_contractor_idx',
        ),
        migrations.RemoveField(
            model_name='project',
            name='billable_rate',
        ),
        migrations.RemoveField(
            model_name='project',
            name='calculated_hours',
        ),
        migrations.RemoveField(
            model_name='projectallocation',
            name='billable_rate_override',
        ),
        migrations.RemoveField(
            model_name='projectallocation',
            name='notes',
        ),
        migrations.DeleteModel(
            name='MonthlyCost',
        ),
        migrations.DeleteModel(
            name='RecurringCost',
        ),
    ]
