# Generated by Django 5.2.1 on 2025-06-02 20:44

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0013_projectallocation_week'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='projectallocation',
            unique_together={('project', 'user_profile', 'year', 'month')},
        ),
        migrations.AlterField(
            model_name='projectallocation',
            name='allocated_hours',
            field=models.DecimalField(decimal_places=1, max_digits=6, validators=[django.core.validators.MinValueValidator(Decimal('0.1'))]),
        ),
        migrations.RemoveField(
            model_name='projectallocation',
            name='is_project_manager',
        ),
        migrations.RemoveField(
            model_name='projectallocation',
            name='week',
        ),
    ]
